### ISSUE TITLE
What's our name?

### ISSUE THREAD

**Issue by rbeyer** [planetarypy/TC#1]
I'm reading through the Astropy documentation, and have learned that Astropy, capitalized, refers to The Astropy Project, while `astropy` lowercase and in backticks refers to the core package.

How shall we refer to this endeavor?  I think it is probably useful to have that same distinction.  We need something that refers to our 'project.'  Should that be: Planetary Python, PlanetaryPy, Planetarypy, something else?

Seems like it should be straightforward to use `planetarypy` for the core package, perhaps adopting an `import planetarypy as planpy` or `import planetarypy as ppy` convention similar to `import numpy as np`?

**Comment by AndrewAnnex** [comment]
The python package should be “planetarypy”, as it gets confusing when a package import name is different than the code base repository (see scikit-learn vs. import sklearn). As for the human readable name I prefer “PlanetaryPy” but it is probably more natural to just do “Planetarypy”. On the import/numpy convention side, I wish there was an obvious solution as the two letter version is rather unfortunate... 

-Andrew Annex

**Comment by michaelaye** [comment]
I agree with package being planetarypy.
I also agree with Andrew that PlanetaryPy somehow reads nicer as a project name, as the word is so long, despite breaking the symmetry with the Astropy project.
And lastly, I'd vote for `import planetarypy as ppy` as the shortest version that isn't `pp` ;)

**Comment by michaelaye** [comment]
But I was also wondering if these kinds of votes should be done in the initial telecon?

**Comment by rbeyer** [comment]
If you want this done in a telecon, then schedule one.

I brought these first two issues up, because I'm noodling with a TSC application, and we need at least that info.

**Comment by rbeyer** [comment]
In our meeting today, we agreed that the project shall be named "PlanetaryPy" and the core package will be called `planetarypy`.  We deferred on establishing a shortened import form.
