### ISSUE TITLE
Request for membership to the PlanetaryPy Technical Committee

### ISSUE THREAD

**Issue by michaelaye** [planetarypy/TC#12]
I suggest that interested parties comment on this issue if they are interested to become a member of the Technical Committee for PlanetaryPy.

The TC is in spirit comparable to the Astropy's Coordination committee, but check our Charter here:
https://github.com/planetarypy/TC/blob/master/Charter.md
and a bunch of more governing documents at https://github.com/planetarypy/TC

As per our charter, we will vote (with lazy consent) during our telecons about any new members.

**Comment by michaelaye** [comment]
I'd like to be a member of the PlanetaryPy TC.

**Comment by rbeyer** [comment]
I'd like to be a member of the PlanetaryPy TC.

**Comment by cmillion** [comment]
I would like to be a member of the PlanetaryPy TC.

**Comment by rbeyer** [comment]
Chase was added with #17

**Comment by michaelaye** [comment]
Closing this for now. New membership can be applied for by contacting the members of the TC.
