### ISSUE TITLE
Pep up the README a bit

### ISSUE THREAD

**Issue by michaelaye** [planetarypy/TC#18]
The main README.md needs a couple of sentences. Not much more I think to avoid duplication with our governing documents. Maybe something like a guided TOC with the links to the documents?

**Comment by rbeyer** [comment]
I suspect that this is now "overcome by events."  With the events being stalling on doing much about this at the time and the opening of the site at https://planetarypy.org ?

Can we close?

**Comment by rbeyer** [comment]
Not seeing any other comment in over a month, closing.
