### ISSUE TITLE
Standing telecon date

### ISSUE THREAD

**Issue by michaelaye** [planetarypy/TC#24]
We thought it's best to decide on a standing telecon data once per month, and to skip it if desired.

In keeping with the Planetary Software scheme of Tuesday telecons, how about having the standing item 

* each third Tuesday in a month?

**Comment by rbeyer** [comment]
I see I'm the only who's given a 'thumbs up' here.  Tomorrow would be the 3rd Tuesday ...

**Comment by michaelaye** [comment]
we agreed during telecon to pick each 3rd Tuesday in a month for now. i'll set up invites.
