### ISSUE TITLE
What should we focus on first?

### ISSUE THREAD

**Issue by rbeyer** [planetarypy/TC#3]
I feel like the title says it all.

However, I have a suggestion: I think we should pick a package, and make it `planetarypy` compliant (whatever we define that to be), and then incorporate it as the first `planetarypy` package.  This will make us conform to our own standards, *before* we admit it to the project.  And then we can go through the process of including it in `planetarypy` which will work out additional kinks.

I think we also need to accept that the existing repos in the planetarypy GitHub org are not *automatically* members of the `planetarypy` package (they have a grandfathered status, clearly), however, I think they are excellent first candidates for this process.

In fact, I think the `pvl` library would be a great first candidate.

**Comment by michaelaye** [comment]
PRO to start with pvl: Trevor seems to be eager to help.

CON: It feels like a very slow start for me, considering how much, I would consider, useful stuff is out there.

Let's discuss...

**Comment by michaelaye** [comment]
The TC expressed the wish to start with a blank canvas, so I guess the next question is, if we start with PVL, we need to figure out if it should stay an AP (affiliated package) or become core.
Do we need another GH issue to start that battle or here is fine?

**Comment by rbeyer** [comment]
I think that's a downstream question.  If we want to use `pvl` as our test, then let's work on shaping it into an 'Affiliated Package.'  Once it passes that bar, then we can discuss whether it stays that way or gets pulled into `planetarypy`.  One step at a time.

So maybe the first thing we really should do is build something like https://github.com/astropy/package-template for `planetarypy`

**Comment by rbeyer** [comment]
In our meeting today, we agreed that the first 'code' that we build should, indeed, be a package template for Affiliated Packages.  Michael volunteered to either get a new repo going, or use the existing cookiecutter-pypackage repo (but I think it has an awkward name, I know why it is named this way, I just like the cleaner 'package-template').

**Comment by rbeyer** [comment]
The package-template is moving along.

I want to reactivate this and ask about affiliated packages, and see if folks have an opinion here.  I think we're *close* to being able to reasonably manage our first affiliated package application.  Is there anything that would prevent us from taking an application and attempting to run the review machine?

**Comment by rbeyer** [comment]
At the [April Meeting](https://github.com/planetarypy/TC/blob/master/Meetings/2020-04-21.md) we decided that we could submit `pvl` and run the process.  Since we are now "doing things" this Issue can now be closed.
