### ISSUE TITLE
google calendar

### ISSUE THREAD

**Issue by AndrewAnnex** [planetarypy/TC#42]
do we have a shared calendar for this project to keep the timezones and rescheduling in check?

**Comment by michaelaye** [comment]
it is my understanding that by me setting the timezone correctly in the event, anybody else using this event would get automatically get the correct time? So I'm not sure what's missing here?

**Comment by michaelaye** [comment]
However, I'd see the use case of a Google calendar that combines all events of our planetary software activities. @rbeyer what do you think? Could/should we add the PPTC meeting to your calendar for the PSTSC?

**Comment by rbeyer** [comment]
We could.  Seems a little silly to create a whole calendar for *just* this meeting.  I think our application to the PSO is just awaiting a final vote, hopefully at the Jan 5 meeting.

**Comment by AndrewAnnex** [comment]
okay sounds like this will be solved soon. Every Tuesday I end up cycling through all the projects github repos to figure out which meeting is happening, once they are consolidated to a single calendar that should improve my situation
