### ISSUE TITLE
Follow up on license : Can one declare a license GH org-wide?

### ISSUE THREAD

**Issue by michaelaye** [planetarypy/TC#5]
Or will every package declare it extra?

**Comment by rbeyer** [comment]
You mean to 'force' every repo in an org to have some license?  No, there's no mechanism for that.  It must be done at least on a per-repo basis via the presences of a LICENSE file.

**Comment by michaelaye** [comment]
Ok, that's what I thought, but wanted to ask if that's something to consider.
