### ISSUE TITLE
Discuss increasing minimum python version from 3.6 to 3.7 due to numpy

### ISSUE THREAD

**Issue by AndrewAnnex** [planetarypy/TC#62]
I recently saw another project choosing to deprecate support for python 3.6 because of the numpy release policy that will remove python 3.6 support by the end of 2021 as discussed in this document from numpy [https://numpy.org/neps/nep-0029-deprecation_policy.html](https://numpy.org/neps/nep-0029-deprecation_policy.html). Alternatively we could set a maximum numpy version limit. But I think the changes needed to update python 3.6 compatible code to 3.7 or newer are fairly minimal, so we should adopt a similar deprecation schedule for the lowest supported python version. Time marches on 

I don't think we need to act too quickly here, and I still need to read this document fully, but it raises some questions regarding our review criteria and external but "core" dependencies like numpy.

**Comment by rbeyer** [comment]
At our [January 2021](https://github.com/planetarypy/TC/blob/master/Meetings/2021-01-26.md) meeting we agreed that:

> the plan is to change the Python version requirement when the current version reaches End of Support. So we will keep our requirement for 3.6 through 2021-12-23, and then switch the requirement to 3.7.

This still seems reasonable to me.

**Comment by michaelaye** [comment]
I also don’t see why we would need to be faster than numpy which seems to have the same plan as us with end of the year ending support for 3.6?

**Comment by AndrewAnnex** [comment]
No I wasn’t advocating to change things before numpy did, I just hadn’t seen the post before. I remembered discussing the 3.7 change a while ago but I think we didn’t discuss how the policies of dependencies effect us which I think is interesting but possibly easy to resolve 

-Andrew Annex

**Comment by rbeyer** [comment]
Is there more to this, or do you think we can close this @AndrewAnnex ?

**Comment by AndrewAnnex** [comment]
closing the issue
